backend:
  name: git-gateway

media_folder: "static/img"
public_folder: "img"

collections:
  - label: "Post" # Used in the UI
    name: "post" # Used in routes, e.g., /admin/collections/blog
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Post Number", name: "num", widget: "number"}
      - {label: "File Size", name: "size", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - label: "Download URL"
        name: "dl"
        widget: "list"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
  - label: "Settings"
    name: "settings"
    files:
      - label: "Site Settings"
        name: "sitesettings"
        file: "config.toml"
        extension: "toml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Site URL", name: "baseURL", widget: "string"}
      - label: "Asset Settings"
        name: "assetsettings"
        file: "data/settings.yml"
        fields:
          - {label: "Header Image", name: "headerimg", widget: "image"}
          - {label: "Site Description", name: "desc", widget: "string"}
